name: dbt_project
version: 1.0.0
config-version: 2

profile: default

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

seeds:
  +schema: analytics
models:
  +schema: analytics